init:
  appId: "516d68fc28e06bb7b8000040"
  orgUrl: "https://hull-demos.hullapp.io"
  debug: false
  sources:
    default: '.'
components:
  game:
    options:
      id: 
  admin:
    options:
      id: 
